# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ruiobo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ruiobo
  pod 'MobileCenter', '~> 0.10.1'
  pod 'RNMobileCenterShared', '~> 0.7.0'

  

  target 'ruioboTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ruiobo-tvOS' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ruiobo-tvOS

  target 'ruiobo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
