/**
 * Created by hebao on 2017/6/13.
 */
'use strict';
export const ACTION_SECURED_KEYBOARD_SHOW = 'ACTION_SECURED_KEYBOARD_SHOW';
export const ACTION_NUMERIC_KEYBOARD_SHOW = 'ACTION_NUMERIC_KEYBOARD_SHOW';